[package]
name = "adventofcode2023"
version = "0.1.0"
edition = "2021"
author = "Matteo Muraca <https://github.com/muraca>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
